### PR TITLE
feat(types): add types for the module configuration and api

### PR DESCRIPTION
**Pull request by rchl**
This adds type for the `nuxtNeo` object in `nuxt.config` and for the `$api` object that is available from different places. The latter is an empty interface that the user would have to extend himself. In the future maybe this could be auto-generated but probably not a trivial task.

TODO:
  - [x] Verify that everything is working as expected
  - [x] Document

### CODE REVIEW

**Comment by rchl** [comment]
This was a bit pain to get right (typescript's extending of modules and ambient modules can be confusing) but I think I got it.

Once this is done, I think we can release new version.

**Comment by ezypeeze** [comment]
> This was a bit pain to get right (typescript's extending of modules and ambient modules can be confusing) but I think I got it.
> 
> Once this is done, I think we can release a new version.

Let me know when you feel like it's ready to review and merge

**Comment by rchl** [comment]
It's ready now. Thanks.

**Review by ezypeeze — APPROVED** [review]

**Comment by rchl** [comment]
> Once this is done, I think we can release a new version.

@ezypeeze I believe I won't be able to trigger a new release since it requires permissions to push to master but feel free to make a release whenever you want.

**Comment by ezypeeze** [comment]
> > Once this is done, I think we can release a new version.
> 
> @ezypeeze I believe I won't be able to trigger a new release since it requires permissions to push to master so feel free to make a release whenever you want.

Released v4.3.0 & updated docs on gh-pages.

Feel free to suggest a better way to publish new releases, you helping alot! 
What is your toughts on better approachs?

**Pull request merged**
